parameters:
  pythonVersions: []
  operatingSystems:
    - 'Linux'
    - 'Windows'
    - 'Mac'
  variants:
    - 'Cython'
    - 'Pure'

stages:
- stage: test
  displayName: 'Run tests'
  variables:
    no_extensions: ''

  jobs:
  - job:

    strategy:
      matrix:
        ${{ each py in parameters.pythonVersions }}:
          ${{ each os in parameters.operatingSystems }}:
            ${{ each variant in parameters.variants }}:
              ${{ if or(eq(os, 'Linux'), eq(variant, 'Cython')) }}:
                ${{ format('Py{0} {1} {2}', py, os, variant) }}:
                  python.version: ${{ py }}
                  ${{ if eq(variant, 'Pure') }}:
                    no_extensions: 'Y'
                  ${{ if eq(os, 'Linux') }}:
                    image: 'ubuntu-latest'
                  ${{ if eq(os, 'Windows') }}:
                    image: 'windows-latest'
                  ${{ if eq(os, 'Mac') }}:
                    image: 'macos-latest'

    pool:
      vmImage: '$(image)'

    timeoutInMinutes: 10

    steps:
    - checkout: self
      clean: true

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'

    - script: |
        python -m pip install --upgrade pip setuptools
      displayName: 'Update pip'

    - script: |
        make cythonize
      condition: and(ne(variables['no_extensions'], 'Y'), succeeded())
      displayName: 'Cythonize'

    - script: |
        pip install -r requirements/dev.txt pytest-azurepipelines
      env:
        FROZENLIST_NO_EXTENSIONS: $(no_extensions)
      displayName: 'Install dependencies'


    - script: |
        pytest tests -vv --no-coverage-upload
      displayName: 'pytest'

    - script: |
        python -m coverage xml
      displayName: 'Prepare coverage'

    - script: |
        pip install codecov
        python -m codecov -f coverage.xml -X gcov
      env:
        CODECOV_TOKEN: $(codecov.token)
      condition: and(variables['codecov.token'], succeeded())
      displayName: 'Upload coverage reports'
