name: python_3_11-dev
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  python_3_11-dev:
    strategy:
      fail-fast: false
      matrix:
        package:
          - frozenlist  # Fails
          - git+https://github.com/aio-libs/frozenlist.git  # Fails
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11-dev
      - run: python3.11 -m pip install --upgrade pip wheel
      - run: python3.11 -m pip install --upgrade Cython
      - run: python3.11 -m pip install ${{ matrix.package }}
